title: "5GNR Workshop"
description: "Learning 5G NR with OpenAirInterface"

# Works for BOTH local and GitHub!
remote_theme: just-the-docs/just-the-docs

search_enabled: true
enable_copy_code_button: true
color_scheme: light
nav_sort: order

baseurl: "/oai-5gnr-workshop"
url: "https://rajeevga.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
