# _config.yml
title: "OAI 5GNR Workshop"
description: "Learning 5G NR with OpenAirInterface"
author: "Rajeev Gangula"
email: r.gangula@northeastern.edu

# Theme
remote_theme: just-the-docs/just-the-docs

# Add these new features
search_enabled: true
enable_copy_code_button: true
color_scheme: light

# Navigation structure
nav_sort: order


# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown processor
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Build settings
baseurl: "/oai-5gnr-workshop" # For GitHub Pages: /repository-name
url: "https://RajeevGa.github.io"
